services:
  qiskit-qward:
    image: jupyter/datascience-notebook
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.qward
    ports:
      - "4321:4321"
    volumes:
      # Mount only essential directories for development
      - ./qward:/home/jovyan/work/qward
      - ./setup.py:/home/jovyan/work/setup.py
      - ./pyproject.toml:/home/jovyan/work/pyproject.toml
      - ./requirements.txt:/home/jovyan/work/requirements.txt
      - ./requirements.qward.txt:/home/jovyan/work/requirements.qward.txt
      - ./.env:/home/jovyan/work/.env
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_PORT=4321
      - PYTHONPATH=/home/jovyan/work
      - JUPYTER_ENABLE_AUTORELOAD=yes
    # We don't need to pip install since it's already done in the Dockerfile
    command: >
      jupyter lab --ip=0.0.0.0 --port=4321 --no-browser

  docs:
    build:
      context: .
      dockerfile: Dockerfile.docs
    ports:
      - "1234:1234"
    volumes:
      - ./docs:/docs/docs
      - ./README.md:/docs/README.md
      - ./requirements.docs.txt:/docs/requirements.docs.txt
    # Package is already installed in the Dockerfile
    command: >
      bash -c "sphinx-build -b html docs docs/_build/html && 
               cd docs/_build/html && 
               python -m http.server 1234"
